import Animatedtext from "@/components/Animatedtext";
import React, { useEffect } from "react";
import Head from "next/head";
import Layout from "@/components/Layout";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-2.jpg";
import { useInView } from "react-intersection-observer";
import { useMotionValue, useSpring } from "framer-motion";
import { useRef } from "react";
import Skills from "@/components/Skills";
import Experience from "@/components/Experience";
import Education from "@/components/Education";
import Transitions from "@/components/Transitions";

const AnimatedNumber = ({ value }) => {
  const ref = useRef(null);
  const motionValue = useMotionValue(0);
  const springValue = useSpring(motionValue, { duration: 3000 });
  const isInView = useInView(ref, { once: true });
  useEffect(() => {
    if (isInView) {
      motionValue.set(value);
    }
  }, [isInView, value, motionValue]);

  useEffect(() => {
    springValue.on("change", (latest) => {
      if (ref.current && latest.toFixed(0) <= value) {
        ref.current.textContent = latest.toFixed(0);
      }
    });
  }, [springValue, value]);

  return <span ref={ref}></span>;
};

const About = () => {
  return (
    <>
      <Head>
        <title>Nageshwar|About page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transitions />

      <main className=" flex w-full flex-col items-center justify-center dark:text-light">
        <Layout className="pt-16">
          <Animatedtext
            text="Dream Design Deliver"
            className="mb-16  lg:!text-7xl sm:!text-6xl  xs:!text-4xl sm:mb-8 "
          />

          <div className="grid w-full grid-cols-8 gap-16 sm:gap-8">
            <div className="col-span-3 flex-col items-start justify-start xl:col-span-4 md:order-2 md:col-span-8">
              <h2 className="mb-4 text-lg font-bold uppercase text-dark/75 dark:text-light/75">
                Digital Insights: Nageshwar&apos;s Story
              </h2>
              <p className="font-medium">
                Welcome to my digital corner. I am Nageshwar, a dedicated
                third-year B.Tech student, specializing in the dynamic realms of
                web development and UI/UX design. Despite being in the early
                stages of my professional journey, I am fueled by a passion for
                crafting digital experiences that seamlessly blend functionality
                and aesthetics. My commitment to staying abreast of industry
                trends and my eagerness to explore innovative solutions define
                my approach to each project.
              </p>

              <p className=" my-4 font-medium">
                In the ever-evolving landscape of design, I firmly believe in
                the transformative power of user-centric solutions. Beyond the
                code and pixels, my focus lies in solving problems and creating
                intuitive, enjoyable experiences for users. Whether it&apos;s
                the architecture of a website, the intricacies of a mobile app,
                or any other digital product, I am driven by the pursuit of
                excellence. As I navigate through this exciting field, I look
                forward to leveraging my growing skills to contribute
                meaningfully to projects that demand a fresh perspective and a
                commitment to design excellence.
              </p>

              <p className="font-medium">
                Thank you for visiting, and I invite you to explore the
                convergence of technology and creativity with me. Together,
                let&apos;s bring your digital visions to life with purposeful
                and aesthetically pleasing solutions.
              </p>
            </div>
            <div
              className="col-span-3  relative h-max rounded-2xl border-2 border-solid border-dark 
            bg-light p-8 dark:bg-dark dark:border-light xl:col-span-4 md:order-1  md:col-span-8"
            >
              <div className=" absolute top-0 -right-3 -z-10 w-[102%] h-[103%]  rounded-[2rem] bg-dark  dark:bg-light" />
              <Image
                src={profilePic}
                alt="Ranveer"
                className=" w-full h-auto rounded-2xl"
                priority
                sizes="(max-width: 768px) 100vw,(max-width: 1200px) 50vw, 33vw"
              />
            </div>
            <div className=" col-span-2 flex flex-col items-end justify-between xl:col-span-8  xl:flex-row xl:items-centern md:order-3 ">
              <div className=" flex flex-col items-end justify-center xl:items-center  ">
                <span className="inline-block text-7xl font-bold  md:text-6xl sm:text-5xl xs:text-4xl">
                  <AnimatedNumber value={1} />+
                </span>
                <h2 className="text-xl font-medium capitalize text-dark/75 dark:text-light/75 xl:text-center md:text-lg sm:text-base xs:text-sm">
                  {" "}
                  satisfied clients
                </h2>
              </div>

              <div className=" flex flex-col items-end justify-center xl:items-center">
                <span className="inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl">
                  <AnimatedNumber value={6} />+
                </span>
                <h2 className="text-xl font-medium capitalize text-dark/75   dark:text-light/75 xl:text-center md:text-lg sm:text-base xs:text-sm">
                  {" "}
                  Projects Complete
                </h2>
              </div>

              <div className=" flex flex-col items-end justify-center xl:items-center">
                <span className="inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl">
                  <AnimatedNumber value={1} />+{" "}
                </span>
                <h2 className="text-xl font-medium capitalize text-dark/75  dark:text-light/75 xl:text-center md:text-lg sm:text-base xs:text-sm">
                  years of experience
                </h2>
              </div>
            </div>
          </div>

          <Skills />
          <Experience />
          <Education />
        </Layout>
      </main>
    </>
  );
};

export default About;
