import Animatedtext from "@/components/Animatedtext";
import React from "react";
import Head from "next/head";
import Layout from "@/components/Layout";

const about = () => {
  return (
    <>
      <Head>
        <title>Ranveer |About page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className=" flex w-full flex-col items-center justify-center">
        <Layout className="pt-16">
          <Animatedtext
            text="Passion Fuels Purpose"/>
        </Layout>
        <div className="grid w-full grid-cols-8 gap-16">
          <div className="col-span-3 flex-col items-start justify-start">
            <h2 className="mb-4 text-lg font-bold uppercase text-dark/75">
              
              Biography
            </h2>
          </div>
        </div>
      </main>
    </>
  );
};

export default about;
