import Animatedtext from '@/components/Animatedtext'
import React from 'react'
import Head from 'next/head'

const about = () => {
  return (
   <>
   <Head>
      <title>About</title>
      <meta name="description" content="Generated by create next app" />


   </Head>

   <main>
    <Animatedtext text="Passion Fuelled By Curiosity" className="!text-6xl !text-left"/>
   </main>
   </>
  )
}

export default about
