import React from "react";
import Head from "next/head";
import Layout from "@/components/Layout";
import Animatedtext from "@/components/Animatedtext";
import Link from "next/link";
import Image from "next/image";
import { GithubIcon } from "@/components/Icons";
import project1 from "../../public/images/projects/crypto-screener-cover-image.jpg";



const FeaturedProjects = ({type, title, summary, img, link, github}) => {
  return (
    <article className="w-full flex items-center justify-between rounded-3xl border boder-solid border-dark bg-light shadow-2xl">
      <Link href={link} target="_blank"
      
      className="w-1/2 cursor-pointer overflow-hidden rounded-lg"
      >

        <Image src={img} alt={title} className="w-full h-auto" />
      </Link>

      <div className="w-1/2 flex flex-col items-start  justify-between pl-6" >
        <span className="text-primary font-medium text-xl">{type}</span>
        <Link href={link} target="_blank">
          <h2>{title}</h2>
        </Link>

        <p>{summary}</p>
        <div>
          <Link href={github} target="_blank">
          
            <GithubIcon />
          </Link>

          <Link href={link} target="_blank">
            
            Visit project
          </Link>
        </div>
      </div>
    </article>
  );
};

const projects = () => {
  return (
    <>
      <Head>
        <title>Ranveer |Projects page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="w-full mb-16 flex flex-col items-center justify-center">
        <Layout className="pt-16">
          <Animatedtext
            text="Imagination Trumps Knowledge!"
            className="mb-16"
          />

          <div className="grid w-full grid-cols-12 gap-24">
            <div className="col-span-12">
              <FeaturedProjects 
              img={project1}
              summary="Crypto Screener Application
              A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
              It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
              local currency."

              link="/"
              type="Featured Project"
              github="/"
              
              
              
              />
            </div>
            <div className="col-span-6">Projects-1</div>

            <div className="col-span-6">Projects-2</div>

            <div className="col-span-12">Featured Projects</div>

            <div className="col-span-6">Projects-3</div>
            <div className="col-span-6">Projects-4</div>
          </div>
        </Layout>

      </main>

    </>

  );

};


export default projects;
