import Layout from '@/components/Layout'
import React from 'react'
import Head from 'next/head'
import Animatedtext from '@/components/Animatedtext'



const Project = () => {
  return (
    <>
     <Head>
        <title>Ranveer |Projects page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Layout>
         <Animatedtext text="Projects" className="mb-16" />
        

        </Layout>
      </main>



    </>
  )
}

export default Project

